FROM ubuntu:22.04

WORKDIR /app

RUN apt update && apt install -y \
    python3.10 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt # Instalar dependencias
COPY src/ .

EXPOSE 8501

CMD ["streamlit", "run", "Home.py", "--server.address", "0.0.0.0", "--server.port", "8501", "--server.headless", "true"]