FROM ubuntu:22.04
WORKDIR /app
RUN apt update
RUN apt install python3.10 -y
RUN apt install python3-pip -y
COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY ./src .

EXPOSE 8501

CMD ["streamlit","run","src/Home.py"]